## Detecting Malicious URL With Machine Learning In Julia
#### Requirement
+ Pkg.add("DataFrames")
+ Pkg.add("ScikitLearn")

In [ ]:
using DataFrames
using ScikitLearn: fit!,fit_transform!,predict,@sk_import


In [2]:
# Loading Data of Urls
urls = readtable("urldata.csv")

420464×2 DataFrames.DataFrame
│ Row    │ ├────────┼
│ 1      │ │ 2      │ │ 3      │ │ 4      │ │ 5      │ │ 6      │ │ 7      │ │ 8      │ │ 9      │ │ 10     │ │ 11     │ 
⋮
│ 420453 │ │ 420454 │ │ 420455 │ │ 420456 │ │ 420457 │ │ 420458 │ │ 420459 │ │ 420460 │ │ 420461 │ │ 420462 │ │ 420463 │ │ 420464 │ 

│ Row    │ url                                                                                                                                                                                                                                                                                        │
├────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 1      │ "diaryofagameaddict.com"                                                                                                                                                                                                                                                                   │
│ 2      │ "espdesign.com.au"                                                                                                                                                                                                                                                                         │
│ 3      │ "iamagameaddict.com"                                                                                                                                                                                                                                                                       │
│ 4      │ "kalantzis.net"                                                                                                                                                                                                                                                                            │
│ 5      │ "slightlyoffcenter.net"                                                                                                                                                                                                                                                                    │
│ 6      │ "toddscarwash.com"                                                                                                                                                                                                                                                                         │
│ 7      │ "tubemoviez.com"                                                                                                                                                                                                                                                                           │
│ 8      │ "ipl.hk"                                                                                                                                                                                                                                                                                   │
│ 9      │ "crackspider.us/toolbar/install.php?pack=exe"                                                                                                                                                                                                                                              │
│ 10     │ "pos-kupang.com/"                                                                                                                                                                                                                                                                          │
│ 11     │ "rupor.info"                                                                                                                   

In [3]:
head(urls,10)

10×2 DataFrames.DataFrame
│ Row │ url                                           │ label │
├─────┼───────────────────────────────────────────────┼───────┤
│ 1   │ "diaryofagameaddict.com"                      │ "bad" │
│ 2   │ "espdesign.com.au"                            │ "bad" │
│ 3   │ "iamagameaddict.com"                          │ "bad" │
│ 4   │ "kalantzis.net"                               │ "bad" │
│ 5   │ "slightlyoffcenter.net"                       │ "bad" │
│ 6   │ "toddscarwash.com"                            │ "bad" │
│ 7   │ "tubemoviez.com"                              │ "bad" │
│ 8   │ "ipl.hk"                                      │ "bad" │
│ 9   │ "crackspider.us/toolbar/install.php?pack=exe" │ "bad" │
│ 10  │ "pos-kupang.com/"                             │ "bad" │

In [15]:
size(urls)

(420464, 2)

In [ ]:
# X Features and Y Labels
X = convert(Array,urls[:url])

420464-element Array{String,1}:
 "diaryofagameaddict.com"                                                                                                                                                                                                                                                                  
 "espdesign.com.au"                                                                                                                                                                                                                                                                        
 "iamagameaddict.com"                                                                                                                                                                                                                                                                      
 "kalantzis.net"                                                                                                    

In [5]:
y = convert(Array,urls[:label])

420464-element Array{String,1}:
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 ⋮    
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"
 "bad"

In [6]:
url_list = []
for i in urls[:url]
    push!(url_list,i)
end

In [7]:
println(url_list)

Any["diaryofagameaddict.com", "espdesign.com.au", "iamagameaddict.com", "kalantzis.net", "slightlyoffcenter.net", "toddscarwash.com", "tubemoviez.com", "ipl.hk", "crackspider.us/toolbar/install.php?pack=exe", "pos-kupang.com/", "rupor.info", "svision-online.de/mgfi/administrator/components/com_babackup/classes/fx29id1.txt", "officeon.ch.ma/office.js?google_ad_format=728x90_as", "sn-gzzx.com", "sunlux.net/company/about.html", "outporn.com", "timothycopus.aimoo.com", "xindalawyer.com", "freeserials.spb.ru/key/68703.htm", "deletespyware-adware.com", "orbowlada.strefa.pl/text396.htm", "ruiyangcn.com", "zkic.com", "adserving.favorit-network.com/eas?camp=19320;cre=mu&grpid=1738&tag_id=618&nums=FGApbjFAAA", "cracks.vg/d1.php", "juicypussyclips.com", "nuptialimages.com", "andysgame.com", "bezproudoff.cz", "ceskarepublika.net", "hotspot.cz", "gmcjjh.org/DHL", "nerez-schodiste-zabradli.com", "nordiccountry.cz", "nowina.info", "obada-konstruktiwa.org", "otylkaaotesanek.cz", "pb-webdesign.net", "p

Excessive output truncated after 524288 bytes.

sk/", "worldzeek.com/wp-admin/includes/pdf", "veitshoechheim-blueht-auf.de/plugins/search/com_jce", "docmitto.computantest.com/old-copy/data/aa898cd3da5d7c3a463c44e2b65f3dea", "theratepayersdefensefund.com/jd/folders/index.htm", "tainos.ru/news/new/LoginVerification.php", "tainos.ru/news/new/login.php?l=_JeHFUq_VJOXJoGYDw_OXK0K0QWHtoGYDw_Product-UserID&amp;userid_JeHJOXK0IDw_JOXK0IDD&amp;userid=", "altomisimali.com/wp-admin/css/colors/blue/bookmark/index.php", "altomisimali.com/wp-admin/css/colors/blue/bookmark/ii.php?rand=13InboxLightaspxn.1774256418&fid.4.1252899642&fid=1&fav.1&rand.13InboxLight.aspxn.1774256418&fid.1252899642&fid.1&fav.1&email=&.rand=13In

In [8]:
# Vectorization 
@sk_import feature_extraction.text: TfidfVectorizer
vectorizer = TfidfVectorizer()

PyObject TfidfVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm=u'l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern=u'(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [9]:
Xf = fit_transform!(vectorizer,url_list)

PyObject <420464x423929 sparse matrix of type '<type 'numpy.float64'>'
	with 2719161 stored elements in Compressed Sparse Row format>

### Split Training and Testting Data


In [ ]:
@sk_import model_selection: train_test_split

PyObject <function train_test_split at 0x7fb6ebb44a28>

In [11]:
X_train, X_test, y_train, y_test = train_test_split(Xf, y, test_size=0.2, random_state=42)

4-element Array{Any,1}:
 PyObject <336371x423929 sparse matrix of type '<type 'numpy.float64'>'
	with 2174977 stored elements in Compressed Sparse Row format>                                   
 PyObject <84093x423929 sparse matrix of type '<type 'numpy.float64'>'
	with 544184 stored elements in Compressed Sparse Row format>                                     
 String["good", "good", "good", "good", "good", "good", "good", "good", "good", "bad"  …  "good", "good", "good", "good", "good", "good", "good", "good", "good", "good"]
 String["good", "good", "good", "good", "good", "good", "good", "good", "good", "good"  …  "bad", "good", "good", "good", "bad", "good", "good", "good", "good", "good"] 

### Model Building

In [12]:
# Using LogisticRegression
@sk_import linear_model: LogisticRegression


PyObject <class 'sklearn.linear_model.logistic.LogisticRegression'>

In [13]:
model = LogisticRegression(fit_intercept=true)
fit!(model, X_train, y_train)

PyObject LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [14]:
## Checking The Accuracy of Our Model
accuracy = sum(predict(model, X_test) .== y_test) / length(y_test)
println("Accuracy of model: $accuracy")

Accuracy of model: 0.9646225012783466
