#### How To Save Machine Learning Model In Julia
##### Pickle Equivalent
+ Pkg.add("JLD")
+ Pkg.add("PyCallJLD")

In [1]:
# Load EDA Packages
using DataFrames

In [2]:
# Load Machine Learning Packages
using ScikitLearn: fit!,fit_transform!,predict,@sk_import

INFO: Recompiling stale cache file /home/rooot/.julia/lib/v0.6/ScikitLearn.ji for module ScikitLearn.


In [4]:
# Load our Data Set
df = readtable("iris.csv")

150×5 DataFrames.DataFrame
│ Row │ sepal_length │ sepal_width │ petal_length │ petal_width │ species     │
├─────┼──────────────┼─────────────┼──────────────┼─────────────┼─────────────┤
│ 1   │ 5.1          │ 3.5         │ 1.4          │ 0.2         │ "setosa"    │
│ 2   │ 4.9          │ 3.0         │ 1.4          │ 0.2         │ "setosa"    │
│ 3   │ 4.7          │ 3.2         │ 1.3          │ 0.2         │ "setosa"    │
│ 4   │ 4.6          │ 3.1         │ 1.5          │ 0.2         │ "setosa"    │
│ 5   │ 5.0          │ 3.6         │ 1.4          │ 0.2         │ "setosa"    │
│ 6   │ 5.4          │ 3.9         │ 1.7          │ 0.4         │ "setosa"    │
│ 7   │ 4.6          │ 3.4         │ 1.4          │ 0.3         │ "setosa"    │
│ 8   │ 5.0          │ 3.4         │ 1.5          │ 0.2         │ "setosa"    │
│ 9   │ 4.4          │ 2.9         │ 1.4          │ 0.2         │ "setosa"    │
│ 10  │ 4.9          │ 3.1         │ 1.5          │ 0.1         │ "setosa"    │
│ 11  │ 5.4          │ 3.7         │ 1.5          │ 0.2         │ "setosa"    │
⋮
│ 139 │ 6.0          │ 3.0         │ 4.8          │ 1.8         │ "virginica" │
│ 140 │ 6.9          │ 3.1         │ 5.4          │ 2.1         │ "virginica" │
│ 141 │ 6.7          │ 3.1         │ 5.6          │ 2.4         │ "virginica" │
│ 142 │ 6.9          │ 3.1         │ 5.1          │ 2.3         │ "virginica" │
│ 143 │ 5.8          │ 2.7         │ 5.1          │ 1.9         │ "virginica" │
│ 144 │ 6.8          │ 3.2         │ 5.9          │ 2.3         │ "virginica" │
│ 145 │ 6.7          │ 3.3         │ 5.7          │ 2.5         │ "virginica" │
│ 146 │ 6.7          │ 3.0         │ 5.2          │ 2.3         │ "virginica" │
│ 147 │ 6.3          │ 2.5         │ 5.0          │ 1.9         │ "virginica" │
│ 148 │ 6.5          │ 3.0         │ 5.2          │ 2.0         │ "virginica" │
│ 149 │ 6.2          │ 3.4         │ 5.4          │ 2.3         │ "virginica" │
│ 150 │ 5.9          │ 3.0         │ 5.1          │ 1.8         │ "virginica" │

In [5]:
head(df,10)

10×5 DataFrames.DataFrame
│ Row │ sepal_length │ sepal_width │ petal_length │ petal_width │ species  │
├─────┼──────────────┼─────────────┼──────────────┼─────────────┼──────────┤
│ 1   │ 5.1          │ 3.5         │ 1.4          │ 0.2         │ "setosa" │
│ 2   │ 4.9          │ 3.0         │ 1.4          │ 0.2         │ "setosa" │
│ 3   │ 4.7          │ 3.2         │ 1.3          │ 0.2         │ "setosa" │
│ 4   │ 4.6          │ 3.1         │ 1.5          │ 0.2         │ "setosa" │
│ 5   │ 5.0          │ 3.6         │ 1.4          │ 0.2         │ "setosa" │
│ 6   │ 5.4          │ 3.9         │ 1.7          │ 0.4         │ "setosa" │
│ 7   │ 4.6          │ 3.4         │ 1.4          │ 0.3         │ "setosa" │
│ 8   │ 5.0          │ 3.4         │ 1.5          │ 0.2         │ "setosa" │
│ 9   │ 4.4          │ 2.9         │ 1.4          │ 0.2         │ "setosa" │
│ 10  │ 4.9          │ 3.1         │ 1.5          │ 0.1         │ "setosa" │

In [6]:
# Checking for Missing Data and Data Types
showcols(df)

150×5 DataFrames.DataFrame
│ Col # │ Name         │ Eltype  │ Missing │
├───────┼──────────────┼─────────┼─────────┤
│ 1     │ sepal_length │ Float64 │ 0       │
│ 2     │ sepal_width  │ Float64 │ 0       │
│ 3     │ petal_length │ Float64 │ 0       │
│ 4     │ petal_width  │ Float64 │ 0       │
│ 5     │ species      │ String  │ 0       │

In [7]:
size(df)

(150, 5)

In [10]:
# Creating our Features
X = convert(Array,df[1:4])

150×4 Array{Float64,2}:
 5.1  3.5  1.4  0.2
 4.9  3.0  1.4  0.2
 4.7  3.2  1.3  0.2
 4.6  3.1  1.5  0.2
 5.0  3.6  1.4  0.2
 5.4  3.9  1.7  0.4
 4.6  3.4  1.4  0.3
 5.0  3.4  1.5  0.2
 4.4  2.9  1.4  0.2
 4.9  3.1  1.5  0.1
 5.4  3.7  1.5  0.2
 4.8  3.4  1.6  0.2
 4.8  3.0  1.4  0.1
 ⋮                 
 6.0  3.0  4.8  1.8
 6.9  3.1  5.4  2.1
 6.7  3.1  5.6  2.4
 6.9  3.1  5.1  2.3
 5.8  2.7  5.1  1.9
 6.8  3.2  5.9  2.3
 6.7  3.3  5.7  2.5
 6.7  3.0  5.2  2.3
 6.3  2.5  5.0  1.9
 6.5  3.0  5.2  2.0
 6.2  3.4  5.4  2.3
 5.9  3.0  5.1  1.8

In [11]:
typeof(X)

Array{Float64,2}

In [13]:
# Target /Outcome
Y = convert(Array,df[5])

150-element Array{String,1}:
 "setosa"   
 "setosa"   
 "setosa"   
 "setosa"   
 "setosa"   
 "setosa"   
 "setosa"   
 "setosa"   
 "setosa"   
 "setosa"   
 "setosa"   
 "setosa"   
 "setosa"   
 ⋮          
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"

In [15]:
typeof(Y)

Array{String,1}

In [16]:
# Model Building
# Using LogisticRegression
@sk_import linear_model: LogisticRegression

INFO: Installing sklearn via the Conda scikit-learn package...


Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/rooot/.julia/v0.6/Conda/deps/usr:

The following NEW packages will be INSTALLED:

    blas:         1.1-openblas                  conda-forge
    openblas:     0.2.20-7                      conda-forge
    scikit-learn: 0.19.1-py27_blas_openblas_201 conda-forge [blas_openblas]

The following packages will be UPDATED:

    numpy:        1.14.0-py27h3dfced4_1                     --> 1.14.1-py27_blas_openblas_200 conda-forge [blas_openblas]
    scipy:        1.0.0-py27hf5f0f52_0                      --> 1.0.0-py27_blas_openblas_201  conda-forge [blas_openblas]

openblas-0.2.2 100% |###############################| Time: 0:00:05   3.16 MB/s
blas-1.1-openb 100% |###############################| Time: 0:00:00 847.32 kB/s
numpy-1.14.1-p 100% |###############################| Time: 0:00:08   1.09 MB/s
scipy-1.0.0-py 100% |###############################| Time: 0:00:19  

PyObject <class 'sklearn.linear_model.logistic.LogisticRegression'>

In [17]:
## Split our data
@sk_import model_selection: train_test_split

PyObject <function train_test_split at 0x7f4fba07a050>

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

4-element Array{Array,1}:
 [4.6 3.6 1.0 0.2; 5.7 4.4 1.5 0.4; … ; 5.8 2.6 4.0 1.2; 7.1 3.0 5.9 2.1]                                                                                                                                                                                         
 [6.1 2.8 4.7 1.2; 5.7 3.8 1.7 0.3; … ; 4.8 3.0 1.4 0.3; 4.8 3.1 1.6 0.2]                                                                                                                                                                                         
 String["setosa", "setosa", "versicolor", "setosa", "setosa", "virginica", "versicolor", "setosa", "setosa", "setosa"  …  "versicolor", "versicolor", "virginica", "virginica", "setosa", "versicolor", "virginica", "setosa", "versicolor", "virginica"]         
 String["versicolor", "setosa", "virginica", "versicolor", "versicolor", "setosa", "versicolor", "virginica", "versicolor", "versicolor"  …  "setosa", "virginica", "setosa", "virginica", "virginica

In [19]:
println(size(X_train))
println(size(y_train))

(120, 4)
(120,)


In [20]:
# Model Fitting
model = LogisticRegression(fit_intercept=true)
fit!(model, X_train, y_train)

PyObject LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [21]:
## Checking The Accuracy of Our Model
accuracy = sum(predict(model, X_test) .== y_test) / length(y_test)
println("Accuracy of model: $accuracy")

Accuracy of model: 1.0


#### Saving Model To Disk

In [28]:
using JLD
using PyCallJLD
# PyCallJLD necessary when you use @sk_import

INFO: Precompiling module PyCallJLD.


In [30]:
JLD.save("logitmodel.jld","model",model)
#@save "logitmodel.jld" model

In [31]:
# jldopen("logitmodel.jld","w") do s
#     write(s,"model",model)
# end

#### Loading our Model

In [35]:
newmodel = JLD.load("logitmodel.jld","model")
# @load "logitmodel" model

PyObject LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:
# newmodel = jldopen("logitmodel.jld","r") do file
#             read(file,"model")
# end

#### Applying our model

In [36]:
## Checking The Accuracy of Our Model
accuracy = sum(predict(newmodel, X_test) .== y_test) / length(y_test)
println("Accuracy of model: $accuracy")

Accuracy of model: 1.0


In [ ]:
# Returned the Same Accuracy

In [ ]:
# Thanks
# J-Secur1ty
# Jesus Saves @ JCharisTech
# Jesse JCharis